<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Course;
use App\Models\Instructor;

class CourseSeeder extends Seeder
{
    public function run()
    {
        $courses = [
            ['course_code' => 'BST-001', 'title' => 'Basic Safety Training (BST)', 'standard_type' => 'STCW', 'imo_course_number' => 'IMO 1.19', 'category' => 'Safety', 'level' => 'Basic', 'duration_hours' => 40, 'duration_days' => 5, 'description' => 'Kursus wajib STCW yang mencakup teknik keselamatan dasar, pertolongan pertama, pemadam kebakaran, dan survival di laut.', 'objectives' => 'Mampu bertahan dalam situasi darurat di laut, memberikan pertolongan pertama, dan menggunakan peralatan keselamatan.', 'prerequisites' => 'Pendidikan dasar, sehat jasmani dan rohani', 'max_participants' => 20, 'passing_score' => 75, 'status' => 'active', 'fee' => 2500000],
            ['course_code' => 'SCRB-001', 'title' => 'Survival Craft & Rescue Boats (SCRB)', 'standard_type' => 'STCW', 'imo_course_number' => 'IMO 1.23', 'category' => 'Safety', 'level' => 'Operational', 'duration_hours' => 24, 'duration_days' => 3, 'description' => 'Pelatihan pengoperasian sekoci penolong, rakit penolong, dan perahu penyelamat.', 'objectives' => 'Mampu mengoperasikan dan memimpin penggunaan sekoci penolong dan rakit penolong.', 'prerequisites' => 'BST Certificate', 'max_participants' => 15, 'passing_score' => 75, 'status' => 'active', 'fee' => 1800000],
            ['course_code' => 'AFF-001', 'title' => 'Advanced Firefighting (AFF)', 'standard_type' => 'STCW', 'imo_course_number' => 'IMO 1.20', 'category' => 'Safety', 'level' => 'Operational', 'duration_hours' => 32, 'duration_days' => 4, 'description' => 'Pelatihan lanjutan pemadam kebakaran di atas kapal termasuk organisasi dan prosedur pemadaman.', 'objectives' => 'Mampu memimpin operasi pemadaman kebakaran di atas kapal.', 'prerequisites' => 'BST Certificate', 'max_participants' => 16, 'passing_score' => 75, 'status' => 'active', 'fee' => 2000000],
            ['course_code' => 'GMDSS-GOC', 'title' => 'GMDSS General Operator Certificate (GOC)', 'standard_type' => 'STCW', 'imo_course_number' => 'IMO 1.25', 'category' => 'Radio Communications', 'level' => 'Operational', 'duration_hours' => 80, 'duration_days' => 10, 'description' => 'Kursus Global Maritime Distress and Safety System untuk operator radio kapal.', 'objectives' => 'Mampu mengoperasikan peralatan GMDSS dan menangani komunikasi darurat.', 'prerequisites' => 'BST Certificate, D-III Nautika', 'max_participants' => 12, 'passing_score' => 70, 'status' => 'active', 'fee' => 4500000],
            ['course_code' => 'BRM-001', 'title' => 'Bridge Resource Management (BRM)', 'standard_type' => 'STCW', 'imo_course_number' => 'IMO 1.22', 'category' => 'Management', 'level' => 'Management', 'duration_hours' => 40, 'duration_days' => 5, 'description' => 'Pelatihan manajemen sumber daya anjungan untuk perwira deck.', 'objectives' => 'Mampu menerapkan manajemen tim yang efektif di anjungan kapal.', 'prerequisites' => 'STCW II/1 Certificate, 12 bulan pengalaman berlayar', 'max_participants' => 15, 'passing_score' => 75, 'status' => 'active', 'fee' => 3000000],
            ['course_code' => 'ECDIS-001', 'title' => 'Electronic Chart Display and Information System (ECDIS)', 'standard_type' => 'STCW', 'imo_course_number' => 'IMO 1.27', 'category' => 'Navigation', 'level' => 'Operational', 'duration_hours' => 40, 'duration_days' => 5, 'description' => 'Pelatihan penggunaan sistem navigasi elektronik ECDIS.', 'objectives' => 'Mampu mengoperasikan ECDIS secara efektif dalam navigasi kapal.', 'prerequisites' => 'STCW II/1 Certificate', 'max_participants' => 12, 'passing_score' => 70, 'status' => 'active', 'fee' => 3500000],
            ['course_code' => 'MFA-001', 'title' => 'Medical First Aid (MFA)', 'standard_type' => 'STCW', 'imo_course_number' => 'IMO 1.14', 'category' => 'Medical', 'level' => 'Operational', 'duration_hours' => 40, 'duration_days' => 5, 'description' => 'Pelatihan pertolongan pertama medis tingkat lanjut untuk perwira kapal.', 'objectives' => 'Mampu memberikan pertolongan pertama medis dan merawat pasien di atas kapal.', 'prerequisites' => 'BST Certificate', 'max_participants' => 16, 'passing_score' => 75, 'status' => 'active', 'fee' => 2500000],
            ['course_code' => 'ERM-001', 'title' => 'Engine Room Resource Management (ERM)', 'standard_type' => 'STCW', 'imo_course_number' => 'IMO 2.07', 'category' => 'Management', 'level' => 'Management', 'duration_hours' => 40, 'duration_days' => 5, 'description' => 'Pelatihan manajemen sumber daya kamar mesin untuk perwira mesin.', 'objectives' => 'Mampu mengelola sumber daya kamar mesin secara efektif.', 'prerequisites' => 'STCW III/1 Certificate, 12 bulan pengalaman', 'max_participants' => 15, 'passing_score' => 75, 'status' => 'active', 'fee' => 3000000],
            ['course_code' => 'OOW-NAV', 'title' => 'Officer in Charge of Navigational Watch (OOW)', 'standard_type' => 'STCW', 'imo_course_number' => 'IMO 7.03', 'category' => 'Navigation', 'level' => 'Operational', 'duration_hours' => 160, 'duration_days' => 20, 'description' => 'Program sertifikasi perwira jaga navigasi sesuai STCW Regulation II/1.', 'objectives' => 'Memperoleh kompetensi sebagai perwira jaga navigasi pada kapal > 500 GT.', 'prerequisites' => 'D-III Nautika, 12 bulan sea service', 'max_participants' => 20, 'passing_score' => 75, 'status' => 'active', 'fee' => 8500000],
            ['course_code' => 'TANKER-OIL', 'title' => 'Basic Training for Oil Tanker', 'standard_type' => 'STCW', 'imo_course_number' => 'IMO 1.01', 'category' => 'Tanker Operations', 'level' => 'Basic', 'duration_hours' => 40, 'duration_days' => 5, 'description' => 'Pelatihan dasar untuk awak kapal tanker minyak sesuai STCW V/1-1.', 'objectives' => 'Memahami bahaya dan tindakan pencegahan dalam operasi kapal tanker minyak.', 'prerequisites' => 'BST Certificate', 'max_participants' => 20, 'passing_score' => 75, 'status' => 'active', 'fee' => 2800000],
            ['course_code' => 'PROFSHIP-001', 'title' => 'Ship Security Officer (SSO)', 'standard_type' => 'IMO', 'imo_course_number' => 'IMO 3.19', 'category' => 'Security', 'level' => 'Operational', 'duration_hours' => 32, 'duration_days' => 4, 'description' => 'Kursus petugas keamanan kapal sesuai ISPS Code dan STCW VI/5.', 'objectives' => 'Mampu melaksanakan tugas dan tanggung jawab sebagai Ship Security Officer.', 'prerequisites' => 'BST Certificate, pengalaman berlayar minimum 6 bulan', 'max_participants' => 20, 'passing_score' => 70, 'status' => 'active', 'fee' => 2200000],
            ['course_code' => 'ISM-001', 'title' => 'ISM Code Internal Auditor', 'standard_type' => 'IMO', 'imo_course_number' => 'IMO 3.11', 'category' => 'Management', 'level' => 'Management', 'duration_hours' => 40, 'duration_days' => 5, 'description' => 'Kursus auditor internal ISM Code untuk petugas SMS perusahaan pelayaran.', 'objectives' => 'Mampu melaksanakan audit internal terhadap implementasi ISM Code.', 'prerequisites' => 'Pengetahuan ISM Code, pengalaman operasional kapal', 'max_participants' => 20, 'passing_score' => 70, 'status' => 'active', 'fee' => 3000000],
        ];

        $instructorIds = Instructor::pluck('id')->toArray();
        foreach ($courses as $i => $course) {
            $course['instructor_id'] = $instructorIds[$i % count($instructorIds)] ?? null;
            Course::create($course);
        }
    }
}